### PR TITLE
fix bug in zero class method

### PR DESCRIPTION
**Pull request by oscarodeigah**
I updated the zero class method to take 3 instead of 4 arguments

### CODE REVIEW

**Comment by finsberg** [comment]
Could you write a test that would fail before but would now pass?

**Comment by oscarodeigah** [comment]
Ok, I can do that.

**Comment by finsberg** [comment]
@oscarodeigah I made a small change to the test you wrote and also added one more test. Can you have a look and see if you want to make any more changes?

**Comment by oscarodeigah** [comment]
@finsberg I have had a look at the test, and I do not have any changes to make.

**Pull request merged**
